version: '3.7'
services:
  # Each container we'll create will have its own service block where we define
  # container name, location of the build and the dockerfile, env file, ports & volumes
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    restart: unless-stopped
    # restart: "no"
    expose: 
      - "3306"
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      -  inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    restart: on-failure
    # restart: "no"
    ports:
      - "443:443"
    volumes:
      - wp_vol:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    restart: on-failure
    expose:
      - "9000"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      device: '/home/ysanchez/mydata/db_vol'
      o: bind
  wp_vol:
    driver: local
    driver_opts:
      type: none
      device: '/home/ysanchez/mydata/wp_vol'
      o: bind

networks:
  inception:
    driver: bridge