version: '3.8'
  services:
    mariadb:
      build: requirements/mariadb/.
      container_name: mariadb
      ports: "3306"
            volumes:
              - db_vol:
    wordpress:
              volumes:
                - wp_vol:
    nginx:
      
  volumes:
    db_vol:
    wp_vol:

  networks:
    
